import { Outfit } from "next/font/google";
import "./globals.css";
import { ToastProvider } from "@/contexts/ToastContext";
import { SessionProvider } from "next-auth/react";
import NavbarWrapper from "@/components/NavbarWrapper";
import Footer from "@/components/Footer";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Invoice App",
  description: "Generated by Next.js",
};

import { auth } from "@/auth";

export default async function RootLayout({ children }) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={outfit.className}>
        <ToastProvider>
          <SessionProvider session={session}>
            <NavbarWrapper />
            {children}
            <Footer />
          </SessionProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
