import { Outfit } from "next/font/google"; // Using Outfit as requested/suggested
import "./globals.css";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Invoice App",
  description: "Generated by Next.js",
};

import { ToastProvider } from "@/contexts/ToastContext";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <ToastProvider>{children}</ToastProvider>
      </body>
    </html>
  );
}
